### PR TITLE
fix getAverage method to sum correctly

### LINKED ISSUE #67: Fix bug for getAverage
Averages displaying with concatenated numbers instead of numbers summed.

### PR DESCRIPTION
**Pull request by tfoxcollis**
## Summary:
The getAverage method in the utils was concatenating strings of numbers.  Added parseInt to fix this.  

## Type of Changes:
- [x] Bug fix
- [ ] Refactor
- [ ] New feature

## Where are the Changes:
utils.js

## How was this tested:
chrome dev tools

## What are the relevant tickets:
closes #67

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const filterById = (id, arr) => {
 
 const getAverage = (arr, attr) => {
   let total = arr.reduce((sum, obj) => {
-    sum += obj[attr];
+    sum += parseInt(obj[attr]);
```
Comment (kendallm360) [inline src/util.js:9]: Way simpler than we thought it would be. You make this look easy

Comment (masaki-kleinkopf) [reply src/util.js:9]: another nice small tweak.
