### PR TITLE
Fix postData so that the Promise must be resolved before fetching updated data from API

### LINKED ISSUE #71: Fix issue with postData api call
Need to fix bug where postData api call is made, and fetch Data executes async.

### PR DESCRIPTION
**Pull request by tfoxcollis**
## Summary:
Data not posting before fetch call completed, added Promise to make sure the fetch returned a response before fetching the data again.  Refactored some functions into smaller chunks.

## Type of Changes:
- [ x ] Bug fix
- [ x ] Refactor
- [ ] New feature

## Where are the Changes:
apiCalls.js
scripts.js

## How was this tested:
Google Chrome Dev Tools

## What are the relevant tickets:
closes #71

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -351,23 +382,9 @@ buttons.forEach((button) => {
   });
 });
 
-postForm.addEventListener("click", () => {
+postForm.addEventListener("click", (event) => {
+  event.preventDefault()
```
Comment (kendallm360) [inline src/scripts.js:386]: Im glad to see a use catch for event.preventDefault outside of forms.

File: src/scripts.js [hunk 2]
```diff
@@ -66,6 +66,40 @@ const userDataInstances = () => {
   });
 };
 
+const setFormData = (event) => {
```
Comment (kendallm360) [inline src/scripts.js:69]: I like how this correction both fixed the bug and broke the function up into smaller more digestible pieces. Much easier to follow now

File: src/scripts.js [hunk 3]
```diff
@@ -66,6 +66,40 @@ const userDataInstances = () => {
...
+  let formData = inputs.reduce((acc, input) => {
+    acc[input.name] = input.value;
+    return acc
+  },{})
+  formData["userID"] = currentUser.id;
+  formData["date"] = getTodaysDate();
+  return formData
+};
+
+const postObject = (event) => {
```
Comment (masaki-kleinkopf) [inline src/scripts.js:81]: nice fix on our bug! makes sense that each time we post we need to then wait for the promise to be fulfilled before we then refetch everything. that is confusing.
