### PR TITLE
update api call to local server. Fix date issue until date picker is …

### LINKED ISSUE #47: Implement local server
Implement getting and posting data from our local server.

### PR DESCRIPTION
**Pull request by tfoxcollis**
…utilized

## Summary:
Updated fetch to new local server.  Updated hard coded date to work with all data sets.

## Type of Changes:
- [ ] Bug fix
- [x] Refactor
- [ ] New feature

## Where are the Changes:
apiCalls.js
scripts.js

## How was this tested:
chrome dev tools

## What are the relevant tickets:
closes #47

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -75,17 +76,18 @@ const fetchUsers = () => {
...
-    .catch((error) =>
-      console.log(error, "Error is coming back from the server")
-    );
 };
 
 const createUserRepo = () => {
   userRepo = new UserRepository(userDataInstances());
   // currentUser = userRepo.findById(11);
   currentUser = userRepo.generateRandomUser();
+  currentDate = "2019/12/18";
```
Comment (kendallm360) [inline src/scripts.js:90]: Nice, I will see what I can do tomorrow to make the date more dynamic but good job getting it to work with the new API

**Review by masaki-kleinkopf — COMMENTED** [review]
nice work on switching our fetch calls to our local server.
